version: '2.1'

services:
    pastebin-postgres:
      image: pastebin-postgres:latest
      container_name: pastebin-postgres
      restart: always
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASS}
      ports:
          - 5432:5432

    pastebin-redis:
      image: pastebin-redis:latest
      container_name: pastebin-redis
      restart: always
      environment:
        - REDIS_PASS=${REDIS_PASS}
      ports:
          - 6379:6379
      volumes:
          - /root/dumps:/data
      command: redis-server --requirepass ${REDIS_PASS}
      mem_limit: 100m

    pastebin-api:
      depends_on:
          - pastebin-redis
          - pastebin-postgres
      image: pastebin-api:latest
      container_name: pastebin-api
      restart: always
      environment:
        - POSTGRES_PASS=${POSTGRES_PASS}
        - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PASS=${REDIS_PASS}
        - CELERY_BROKER_URL=${CELERY_BROKER_URL}
        - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        - SPACES_URL=${SPACES_URL}
        - SPACES_KEY=${SPACES_KEY}
        - SPACES_SECRET=${SPACES_SECRET}
      volumes:
        - /root/cache:/cache
      ports:
        - 5000:5000
